// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCziVdFLCB-8EK1XJAg1uxlYcmuUvag4Ac',
    appId: '1:122024345464:web:54dfed9aacb417708bd28d',
    messagingSenderId: '122024345464',
    projectId: 'fire-write-c6b35',
    authDomain: 'fire-write-c6b35.firebaseapp.com',
    storageBucket: 'fire-write-c6b35.appspot.com',
    measurementId: 'G-10L1QG9ZHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQgJ-O6D4_oBy9-M7VAIDtNPJu5tzOvw',
    appId: '1:122024345464:android:7eca84c5504edc5e8bd28d',
    messagingSenderId: '122024345464',
    projectId: 'fire-write-c6b35',
    storageBucket: 'fire-write-c6b35.appspot.com',
  );
}
